version: '3'

services:
  database:
    restart: always
    container_name: blockchain-store-db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bloackchain-db
    volumes:
      - ./database/postgres:/data/postgres
    ports:
      - "5432:5432"